### ISSUE TITLE
Issue in Starting Meeting 

### ISSUE THREAD

**Issue by Nitinbhoyar** [mokriya-org/react-native-zoom-us-bridge#10]
When  i'm trying to start meeting with 

 await RNZoomUsBridge.startMeeting(
         meetingId,
          userName,
          userId,
          userZoomAccessToken,
        );
 It throws an exception saying 'RNZoomUsBridge.startMeeting' got 6 parameters but expecting .
Rest of work like join meeting and other functionalities woking fine. 

## React Native version: 0.59.5

Any help will be appreciating

**Comment by fathima-shamsu** [comment]
SAME ISSUE

**Comment by Nitinbhoyar** [comment]
Solved issues by providing one extra email parameter in RNZoomUsBridge.startMeeting() function 
 example :  await RNZoomUsBridge.startMeeting(
meetingId,
userName,
userId,
userZoomAccessToken,
userEmail
);

Note : userEmail should be associated with zoom account.

**Comment by fathima-shamsu** [comment]
> Solved issues by providing one extra email parameter in RNZoomUsBridge.startMeeting() function
> example : await RNZoomUsBridge.startMeeting(
> meetingId,
> userName,
> userId,
> userZoomAccessToken,
> userEmail
> );
> 
> Note : userEmail should be associated with zoom account.

still cant start meeting

**Comment by davinderom** [comment]
Check if you are getting username null. replace it with some static string and check if it works
