### ISSUE TITLE
Application getting crashed after added "react-native-screens": "^2.5.0"

### ISSUE THREAD

**Issue by udara1999** [mokriya-org/react-native-zoom-us-bridge#37]
After add all these libraries my react-native application getting crashed continuously 
anyone can help?

 "@mokriya/react-native-zoom-us-bridge": "0.0.5",
    "@react-native-community/async-storage": "^1.12.1",
    "axios": "^0.21.0",
    "js-base64": "^3.6.0",
    "md5": "^2.2.1",
    "qs": "^6.9.4",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-root-siblings": "^4.0.6",
    "react-native-root-toast": "^3.2.1",
    "react-native-screens": "^2.5.0",
    "react-native-vector-icons": "^7.1.0",
    "react-navigation": "^3.11.1"

**Comment by vparamas-cn** [comment]
@udara1999 do you find a solution for this issue, please help me

**Comment by udara1999** [comment]
@vparamas-cn  yes it's workers after adding largeheep true in android manifest file

**Comment by vparamas-cn** [comment]
I have added a large heap true in an android manifest file, still, I'm getting an error 

@udara1999  Any other setting need to update?
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.doctall">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
    <uses-feature android:name="android.hardware.microphone" android:required="false" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      **android:largeHeap="true"**
      android:theme="@style/AppTheme"
      android:usesCleartextTraffic="true" 
      android:requestLegacyExternalStorage="true">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <provider
        android:name="com.vinzscam.reactnativefileviewer.FileProvider"
        android:authorities="${applicationId}.provider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/file_viewer_provider_paths"
        />
    </provider>
    </application>

</manifest>

**Comment by udara1999** [comment]
@vparamas-cn no after add largeHeap true it's working perfectly
