### ISSUE TITLE
TypeError: Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by gabrielbabierra** [mokriya-org/react-native-zoom-us-bridge#7]
I inserted this inside my javascript code
> import RNZoomUsBridge from '@mokriya/react-native-zoom-us-bridge';
> 
> RNZoomUsBridge.initialize(
>   ZOOM_APP_KEY,
>   ZOOM_APP_SECRET,
> );

As instructed from your documentations. Then i got an error in android saying 'TypeError: Cannot read property 'initialize' of undefined'. Followed the procedures accordingly based from the documentations. My react native version is 61.2.

It seems that i need to manually install it and add lines on my android codes. Here are the steps i did to bypass this issue:

**Inserted in android/settings.gradle**
include ':@mokriya_react-native-zoom'
project(':@mokriya_react-native-zoom').projectDir = new File(rootProject.projectDir, '../node_modules/@mokriya/react-native-zoom-us-bridge/android')

**android/app/build.gradle**
implementation project(':@mokriya_react-native-zoom')

**android/app/src/main/java/com/bridged/MainApplication.java**
_On top of the imports_
import com.mokriya.zoomus.RNZoomUsBridgePackage;
_then at the getPackages_
new RNZoomUsBridgePackage()

Then the issue solved. 

Thanks

**Comment by jimji1005** [comment]
@gabrielbabierra I took a quick look at the issue. 

I started with a new project with 61.2, auto link was able to link the library.

I also tested `react-native link` and it added the proper lines to settings.gradle 
```include ':@mokriya_react-native-zoom-us-bridge'
project(':@mokriya_react-native-zoom-us-bridge').projectDir = new File(rootProject.projectDir, '../node_modules/@mokriya/react-native-zoom-us-bridge/android')
```

Are you using manual linking?
